python run.py   --prefix [time] --gpu 5 \
                --dataset wmt16-deen --language deen --load_vocab \
                --level subword \
                --load_from 10.24_18.16.wmt16-deen_subword_fast_512_512_6_8_0.100_16000___ \
                --teacher 10.17_08.22.wmt16-ende_subword_512_512_6_8_0.100_16000___ \
                --use_mask  --diag --positional_attention \
                --use_wo --share_embeddings \
                --preordering --use_posterior_order --fertility_only \
                --remove_eos \
                --fertility_mode argmax \
                --mode test \
                --batchsize 20000 \
                --fast \
                --test_set newstest2013 \
