python run.py   --prefix [time] --gpu 7 \
                --dataset wmt16-ende --language ende --load_vocab \
                --level subword \
                --teacher 10.10_23.04.wmt16-ende_subword_512_512_6_8_0.100_16000___ \
                --load_from 10.25_19.15.wmt16-ende_subword_fast_512_512_6_8_0.100_16000___  \
                --use_mask  --diag --positional_attention \
                --use_wo --share_embeddings \
                --preordering --use_posterior_order --fertility_only \
                --remove_eos \
                --fertility_mode argmax \
                --mode test_noisy \
                --fast \
                --batchsize 100 \
                --beam_size 10  --alpha 1 \
                --test_set newstest2014 \
